version: "3.8"

services:
    grpc_server:
        container_name: "go_grpc"
        build: .
        ports:
            - "50051:50051"
        links:
            - redis
        
    redis:
        container_name: "redis"
        image: redis:alpine
        command: redis-server --requirepass 0000
        ports: 
            - "6379:6379"